version: "3"
services:
  nodejs:
    image: node:latest
    container_name: nodejs
    restart: always
    ports:
      - 80:8080
    environment:
      DATABASE_URL: mongodb://localhost:27017/sea
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./:/usr/app
#      - ./docker/logs/node:root/.npm/_logs
    working_dir: /usr/app
    command: bash -c "npm install && npm start"
  db:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="admin"
      - MONGODB_PASS="12345Qq"
    volumes:
      - ./docker/data/mongo:/data/db
#      - ./docker/logs/mongo:/dev/null
    command: mongod --smallfiles --logpath=/dev/null # --quiet